name: SourceMod Workflow

on:
  push:
    branches:
    - '*'
    - 'map-names-tiers'
  pull_request:
    branches:
    - 'main'
    - 'map-names-tiers'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download sourcemod
      run: |
        wget "http://www.sourcemod.net/latest.php?version=1.10&os=linux" -O sourcemod.tar.gz
        tar -xzf sourcemod.tar.gz
    - name: Download Dependencies
      run: |
        wget "https://github.com/Bara/Multi-Colors/archive/refs/heads/master.zip" -O MultiColors.zip
        unzip MultiColors.zip
        mkdir -p addons/sourcemod/scripting/include
        mv * addons/sourcemod/scripting/include
    - name: Give spcomp the required permissions
      run: chmod +x addons/sourcemod/scripting/spcomp
    - name: Compiling the plugin
      run: |
        addons/sourcemod/scripting/spcomp -E addons/sourcemod/scripting/mapchooser_extended.sp
        addons/sourcemod/scripting/spcomp -E addons/sourcemod/scripting/nominateions_extended.sp
        addons/sourcemod/scripting/spcomp -E addons/sourcemod/scripting/rockthevote_extended.sp
